# Generated by Django 4.2.10 on 2024-02-28 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import survey.models.category
import survey.models.question
import survey.models.survey


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Name")),
                (
                    "order",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Display order"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "random_order",
                    models.IntegerField(
                        default=survey.models.category.random_number,
                        verbose_name="random order",
                    ),
                ),
                (
                    "display_num",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        verbose_name="Number of questions displayed",
                    ),
                ),
                (
                    "hiding_question_order",
                    models.CharField(
                        blank=True,
                        default="0",
                        max_length=6,
                        null=True,
                        verbose_name="This determines whether the hidden question is displayed in the category.There is not hiding question when sitting 0.",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("one-random", "one-random"),
                            ("sequence", "sequence"),
                        ],
                        default="sequence",
                        max_length=200,
                        verbose_name="block type",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Users can see it and answer it"
                    ),
                ),
                (
                    "need_logged_user",
                    models.BooleanField(
                        verbose_name="Only authenticated users can see it and answer it"
                    ),
                ),
                (
                    "editable_answers",
                    models.BooleanField(
                        default=True,
                        verbose_name="Users can edit their answers afterwards",
                    ),
                ),
                (
                    "display_method",
                    models.SmallIntegerField(
                        choices=[
                            (1, "By question"),
                            (2, "By category"),
                            (0, "All in one page"),
                        ],
                        default=1,
                        verbose_name="Display method",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Template"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "expire_date",
                    models.DateField(
                        blank=True,
                        default=survey.models.survey.in_duration_day,
                        verbose_name="Expiration date",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(blank=True, verbose_name="Redirect URL"),
                ),
                (
                    "diagnosis_stages_qs_num",
                    models.IntegerField(default=10, verbose_name="Diagnosis of stages"),
                ),
            ],
            options={
                "verbose_name": "survey",
                "verbose_name_plural": "surveys",
                "permissions": (
                    ("participant", "Questionnaires can be filled out"),
                    ("experimenter", "Possibility to edit the survey"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "Majority_Rate",
                    models.CharField(
                        default="0", max_length=20, verbose_name="Majority Rate"
                    ),
                ),
                (
                    "Correctness_Rate",
                    models.CharField(
                        default="0", max_length=20, verbose_name="Correctness Rate"
                    ),
                ),
                (
                    "interview_uuid",
                    models.CharField(
                        max_length=36, verbose_name="Interview unique identifier"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="survey.survey",
                        verbose_name="Survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set of answers to surveys",
                "verbose_name_plural": "Sets of answers to surveys",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("order", models.IntegerField(verbose_name="Order")),
                ("required", models.BooleanField(verbose_name="Required")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("select", "select"),
                            ("text", "text (multiple line)"),
                            ("short-text", "short text (one line)"),
                            ("radio", "radio"),
                            ("select-multiple", "Select Multiple"),
                            ("select_image", "Select Image"),
                            ("integer", "integer"),
                            ("float", "float"),
                            ("date", "date"),
                        ],
                        default="select",
                        max_length=200,
                        verbose_name="Type",
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="\n    The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .\nWhen entering options, use \"|\" to separate different options. For example, a|b|c.\n\n",
                        null=True,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "subsidiary_type",
                    models.CharField(
                        choices=[
                            ("majority_minority", "majority_minority"),
                            ("certainty_degree", "certainty_degree"),
                        ],
                        default="majority_minority",
                        max_length=100,
                        verbose_name="subsidiary_type",
                    ),
                ),
                (
                    "majority_minority",
                    models.CharField(
                        choices=[("majority", "多数派"), ("minority", "少数派")],
                        default="majority",
                        max_length=200,
                        verbose_name="majority_minority",
                    ),
                ),
                (
                    "certainty_degree",
                    models.IntegerField(default=50, verbose_name="degree of certainty"),
                ),
                ("majority_choices", models.CharField(default="Null", max_length=200)),
                (
                    "hiding_question_category_order",
                    models.IntegerField(
                        default=0, verbose_name="hiding_question_category_order"
                    ),
                ),
                (
                    "random_order_q",
                    models.IntegerField(
                        default=survey.models.question.random_number,
                        verbose_name="random_order_q",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="survey.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="survey.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ("survey", "order"),
            },
        ),
        migrations.AddField(
            model_name="category",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="survey.survey",
                verbose_name="Survey",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                (
                    "subsidiary",
                    models.CharField(
                        choices=[("majority", "多数派"), ("minority", "少数派")],
                        default="majority",
                        max_length=9,
                        verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.response",
                        verbose_name="Response",
                    ),
                ),
            ],
        ),
    ]
