# Generated by Django 4.2.10 on 2024-02-28 11:38

from django.db import migrations, models
import django.utils.timezone
import survey.models.question
import survey.models.survey


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("minority", "少数派"), ("majority", "多数派")],
                default="majority",
                max_length=9,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="block_type",
            field=models.CharField(
                choices=[("one-random", "one-random"), ("sequence", "sequence")],
                default="sequence",
                help_text="\n\n",
                max_length=200,
                verbose_name="block type",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="\n\n",
                max_length=2000,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_num",
            field=models.IntegerField(
                blank=True,
                default=10,
                help_text="\n\n",
                verbose_name="Number of questions displayed",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="hiding_question_order",
            field=models.CharField(
                blank=True,
                default="0",
                help_text='\nThis determines whether the hidden question is displayed in the category.\nThere is not hiding question when sitting 0.\nIf there are multiple locations where hidden questions need to be inserted, please use "|" to separate them. \nFor example, "1 | 3" indicates that the first and third questions are hidden questions.\n',
                max_length=6,
                null=True,
                verbose_name="a",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="\n\n", max_length=400, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.IntegerField(
                blank=True, help_text="\n\n", null=True, verbose_name="Display order"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="certainty_degree",
            field=models.IntegerField(
                default=50, help_text="\n\n", verbose_name="degree of certainty"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="hiding_question_category_order",
            field=models.IntegerField(
                default=0,
                help_text="\n\n",
                verbose_name="hiding_question_category_order",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="majority_choices",
            field=models.CharField(default="Null", help_text="\n\n", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="majority_minority",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                help_text="\n\n",
                max_length=200,
                verbose_name="majority_minority",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(help_text="\n\n", verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="question",
            name="random_order_q",
            field=models.IntegerField(
                default=survey.models.question.random_number,
                help_text="\n\n",
                verbose_name="random_order_q",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="required",
            field=models.BooleanField(help_text="\n\n", verbose_name="Required"),
        ),
        migrations.AlterField(
            model_name="question",
            name="subsidiary_type",
            field=models.CharField(
                choices=[
                    ("majority_minority", "majority_minority"),
                    ("certainty_degree", "certainty_degree"),
                ],
                default="majority_minority",
                help_text="\n\n",
                max_length=100,
                verbose_name="subsidiary_type",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(help_text="\n\n", verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("select", "select"),
                    ("text", "text (multiple line)"),
                    ("short-text", "short text (one line)"),
                    ("radio", "radio"),
                    ("select-multiple", "Select Multiple"),
                    ("select_image", "Select Image"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("date", "date"),
                ],
                default="select",
                help_text="\n\n",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=models.TextField(help_text="\n\n", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="diagnosis_stages_qs_num",
            field=models.IntegerField(
                default=10, help_text="\n\n", verbose_name="Diagnosis of stages"
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="expire_date",
            field=models.DateField(
                blank=True,
                default=survey.models.survey.in_duration_day,
                help_text="\n\n",
                verbose_name="Expiration date",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="\n\n",
                verbose_name="Users can see it and answer it",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(
                help_text="\n\n", max_length=400, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="publish_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="\n\n",
                verbose_name="Publication date",
            ),
        ),
    ]
