# Generated by Django 4.1 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_answer_subsidiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="random_order",
            field=models.IntegerField(default=298994, verbose_name="random order"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("minority", "少数派"), ("majority", "多数派")],
                default="majority",
                max_length=9,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
    ]
