# Generated by Django 4.2.10 on 2024-02-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_alter_answer_subsidiary_alter_category_block_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="random_order",
        ),
    ]
