# Generated by Django 4.1 on 2024-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_alter_answer_subsidiary_alter_category_random_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_num",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Number of questions displayed"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="certainty_degree",
            field=models.IntegerField(default=50, verbose_name="degree of certainty"),
        ),
        migrations.AddField(
            model_name="question",
            name="majority_choices",
            field=models.CharField(default="Null", max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="majority_minority",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                max_length=200,
                verbose_name="majority_minority",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("select", "select"),
                    ("text", "text (multiple line)"),
                    ("short-text", "short text (one line)"),
                    ("radio", "radio"),
                    ("select-multiple", "Select Multiple"),
                    ("select_image", "Select Image"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("date", "date"),
                ],
                default="text",
                max_length=200,
                verbose_name="Type",
            ),
        ),
    ]
