# Generated by Django 4.2.10 on 2024-02-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey",
            "0004_remove_question_random_order_q_response_repeat_order_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("Initial state", "Initial state"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="Initial state",
                max_length=50,
                verbose_name="completion_status",
            ),
        ),
    ]
