# Generated by Django 4.1 on 2024-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_category_display_num_question_certainty_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subsidiary_type",
            field=models.CharField(
                choices=[
                    ("majority_minority", "majority_minority"),
                    ("certainty_degree", "certainty_degree"),
                ],
                default="majority_minority",
                max_length=100,
                verbose_name="subsidiary_type",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="\n    The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .\nWhen entering options, use \"|\" to separate different options. For example, a|b|c.\n\n",
                null=True,
                verbose_name="Choices",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="majority_minority",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                max_length=200,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
    ]
