# Generated by Django 4.1 on 2024-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_alter_response_options_alter_answer_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="random_order_q",
            field=models.IntegerField(
                blank=True, default=1, verbose_name="random_order_q"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                max_length=9,
                verbose_name="Majority vs. Minority",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="block_type",
            field=models.CharField(
                choices=[("one-random", "one-random"), ("sequence", "sequence")],
                default="sequence",
                help_text="\n\n",
                max_length=200,
                verbose_name="block type",
            ),
        ),
    ]
