# Generated by Django 4.2.10 on 2024-02-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_question_subsidiary_type_alter_question_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("minority", "少数派"), ("majority", "多数派")],
                default="majority",
                max_length=9,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
    ]
