# Generated by Django 4.1 on 2024-02-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_alter_answer_subsidiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="diagnosis_stages_qs_num",
            field=models.IntegerField(default=0, verbose_name="Diagnosis of stages"),
        ),
    ]
