# Generated by Django 4.1 on 2024-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0008_survey_diagnosis_stages_qs_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                max_length=9,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="diagnosis_stages_qs_num",
            field=models.IntegerField(default=10, verbose_name="Diagnosis of stages"),
        ),
    ]
