# Generated by Django 4.1 on 2024-02-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_alter_answer_subsidiary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="Correctness_Rate",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Correctness Rate"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="Majority_Rate",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Majority Rate"
            ),
        ),
    ]
