# Generated by Django 4.2.10 on 2024-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0010_response_correctness_rate_response_majority_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("select", "select"),
                    ("text", "text (multiple line)"),
                    ("short-text", "short text (one line)"),
                    ("radio", "radio"),
                    ("select-multiple", "Select Multiple"),
                    ("select_image", "Select Image"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("date", "date"),
                ],
                default="select",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="display_method",
            field=models.SmallIntegerField(
                choices=[
                    (1, "By question"),
                    (2, "By category"),
                    (0, "All in one page"),
                ],
                default=1,
                verbose_name="Display method",
            ),
        ),
    ]
