# Generated by Django 4.2.10 on 2024-02-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0011_alter_question_type_alter_survey_display_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="display_num",
            field=models.IntegerField(
                blank=True, default=1, verbose_name="Number of questions displayed"
            ),
        ),
    ]
