# Generated by Django 4.2.10 on 2024-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0012_alter_category_display_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="display_num",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Number of questions displayed"
            ),
        ),
    ]
