# Generated by Django 3.2.8 on 2021-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0013_auto_20200609_0748"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="redirect_url",
            field=models.URLField(blank=True, verbose_name="Redirect URL"),
        ),
    ]
