# Generated by Django 4.2.10 on 2024-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0015_question_hiding_question_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="subsidiary",
            field=models.CharField(
                choices=[("majority", "多数派"), ("minority", "少数派")],
                default="majority",
                max_length=9,
                verbose_name="前の質問で、あなたが答えた回答は多数派だと想いますか、少数派だと思いますか？",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="hiding_question_category_order",
            field=models.IntegerField(default=0, verbose_name="88"),
        ),
    ]
